### ISSUE TITLE
404 | Page could not be found

### ISSUE THREAD

**Issue by Zemerik** [mdtanvirahamedshanto/Space-Portfolio-Nextjs#1]
Hey, 

The `Skills` and `Projects` pages of your website are inaccessible for users. 

![image](https://github.com/mdtanvirahamedshanto/Space-Portfolio-Nextjs/assets/133865660/a4139a99-9fe8-445e-9d3a-58bde6091319)

**Comment by mdtanvirahamedshanto** [comment]
this is an old project for practice

**Comment by Zemerik** [comment]
oh ok. Thanks for replying
